### PR TITLE
log-based distance function.

### PR DESCRIPTION
**Pull request by dkorolev**
Hi @mzhurovich ,

Sorry for a small mess with `make indent`. The log-based distance function works.

I'll move model optimization to a dedicated thread to a) make the startup faster, and b) avoid gaps in time series while the model is being trained.

PTAL at the maths.

Thanks,
Dima

### CODE REVIEW

**Comment by dkorolev** [comment]
@mzhurovich : And moved image re-generation into its own thread. PTAL!

**Comment by dkorolev** [comment]
Good to look at.

**Comment by mzhurovich** [comment]
@dkorolev 
It's definitely better than previous version, but there are still some issues.
1) For the pair with 1A/0D I get much bigger distance than for 1A/1D, which is strange
2) The function behaves like Rosenbrock, i.e. it's pretty flat and hard to optimize
We could tune optimizer a bit, as we don't need to be super-precise here:
set `bt_beta` to 0.5 and `grad_eps` to at least 0.5
But IMHO we could think if we can derive a better cost-function for this demo.

**Comment by dkorolev** [comment]
@mzhurovich : PTAL, added

```
          params.SetValue("bt_beta", 0.5);
          params.SetValue("grad_eps", 0.5);
```

Thanks,
Dima

**Comment by mzhurovich** [comment]
@dkorolev LGTM. Merging.

**Pull request merged**
